apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "java-springboot.fullname" . }}-app-deployment
  labels:
  {{- include "java-springboot.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.appDeployment.replicas }}
  selector:
    matchLabels:
      app: my-app
    {{- include "java-springboot.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: my-app
      {{- include "java-springboot.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.appDeployment.myImage.image.repository }}:{{ .Values.appDeployment.myImage.image.tag
          | default .Chart.AppVersion }}
        name: my-image
        ports:
        - containerPort: 8080
        resources: {}