apiVersion: v1
kind: Service
metadata:
  name: node-service
  labels:
  {{- include "node-js.labels" . | nindent 4 }}
spec:
  type: {{ .Values.nodeService.type }}
  selector:
    app: my-app-node-js
  {{- include "node-js.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.nodeService.ports | toYaml | nindent 2 -}}
