---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-node-js
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app-node-js
  template:
    metadata:
      labels:
        app: my-app-node-js
    spec:
      containers:
      - name: my-image-node-js
        image: devopsmela/node-js:v1
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: node-service
spec:
  type: NodePort
  ports:
  - port: 5000
  selector:
    app: my-app-node-js
