---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace:
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-image
        image: devopsmela/case-1-springboot
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: my-app        